import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F8F8",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  image: {
    width: 247,
    height: 191,
    marginTop: 64,
    marginBottom: 8,
  },
  containerText: {
    flex: 1,
    backgroundColor: "rgba(133, 170, 159, 0.1)",
    paddingTop: 32,
    paddingHorizontal: 16,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  title: {
    fontFamily: "FixelDisplaySemiBold",
    fontSize: 30,
    letterSpacing: -0.02 * 30,
    color: "#121417",
    marginBottom: 16,
  },
  subtitle: {
    fontFamily: "FixelDisplayRegular",
    fontSize: 16,
    lineHeight: 24,
    color: "rgba(18, 20, 23, 0.8)",
    marginBottom: 16,
  },
  input: {
    width: 343,
    height: 56,
    borderRadius: 15,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderColor: "rgba(133, 170, 159, 0.1)",
    borderWidth: 1,
    fontFamily: "FixelDisplayRegular",
    fontSize: 16,
    lineHeight: 24,
    color: "#121417",
    marginBottom: 14,
  },
  button: {
    width: 343,
    height: 56,
    backgroundColor: "#85AA9F",
    borderRadius: 30,
    padding: 16,
    alignItems: "center",
    marginTop: 14,
    marginBottom: 16,
  },
  buttonText: {
    fontFamily: "FixelDisplayBold",
    color: "#FCFCFC",
    fontSize: 16,
  },
  loginText: {
    fontFamily: "FixelDisplayBold",
    color: "rgba(18, 20, 23, 0.5)",
    textDecorationLine: "underline",
    textAlign: "center",
  },
  error: {
    color: "red",
    fontSize: 12,
    alignSelf: "flex-start",
  },
});
